### ISSUE TITLE
0.0.6 version breaks with TypeError: tar.Extract is not a function

### ISSUE THREAD

**Issue by alansouzati** [joshuah/tarball-extract#14]
With 0.0.5 I was able to call extractTarball successfully.

I updated to 0.0.6 and did not change anything in my [code](https://github.com/grommet/grommet-toolbox/blob/master/src/gulp-tasks-pack.js#L35). Now I'm getting the following error:

```
node_modules/tarball-extract/tarball.js:11
    .pipe(tar.Extract({ path: destination}))
              ^

TypeError: tar.Extract is not a function
```

**Comment by matsieftw** [comment]
hm. What version of tar is tarball-extract using? It should be using 2.2.1. This shouldn't be an issue if it's using 2.2.1. Whereas if it's still using *, the tar API has changed and I have not updated the package yet to use the new API.

**Comment by alansouzati** [comment]
I'm using tarball-extract version 0.0.6. Where is 2.2.1 available? In NPM 0.0.6 is the latest. Sorry if I'm missing something.

https://www.npmjs.com/package/tarball-extract

**Comment by matsieftw** [comment]
0.0.6 is the correct version for tarball-extract. It uses version 2.2.1 of tar. You need to run `npm update --depth=9999` to update packages and their dependencies recursively.

**Comment by alansouzati** [comment]
I actually deleted my node_modules, and installed again with `yarn install`. that's how I reproduced this issue. Let me validate the version of tar that is being downloaded

**Comment by alansouzati** [comment]
Yeah I was using version 0.0.3, my bad.
